var gigs = '[{'
+ '"gigs": [\n'
    + '{\n'
      + '"date": "Saturday, May 24, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/thestarcharters\\" target=\\"_blank\\">The Star Charters</a> and <a href=\\"https://www.facebook.com/profile.php?id=61574993265607\\" target=\\"_blank\\">Northwoods</a>",\n'
      + '"location": "<a href=\\"https://www.facebook.com/peterboroughcontra\\" target=\\"_blank\\">Peterborough, NH</a>",\n'
      + '"event": "Spring Blossom Ball double dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Friday, May 30, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/cojiroduo\\" target=\\"_blank\\">Cojiro</a>",\n'
      + '"location": "<a href=\\"https://www.danceflurry.org/series/albany-contradance/\\" target=\\"_blank\\">Albany, NY</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, May 31, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/cojiroduo\\" target=\\"_blank\\">Cojiro</a>",\n'
      + '"location": "<a href=\\"https://www.hudsonvalleydance.org/contra\\" target=\\"_blank\\">Poughkeepsie, NY</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Friday, June 6, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/thestarcharters\\" target=\\"_blank\\">The Star Charters</a>",\n'
      + '"location": "<a href=\\"https://seacoastcontra.com/\\" target=\\"_blank\\">Newfields, NH</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, June 7, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/thestarcharters\\" target=\\"_blank\\">The Star Charters</a>",\n'
      + '"location": "<a href=\\"https://folkproject.org/swingin-tern/\\" target=\\"_blank\\">Chatham, NJ</a>",\n'
      + '"event": "Double contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, June 21, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/thestarcharters\\" target=\\"_blank\\">The Star Charters</a>",\n'
      + '"location": "<a href=\\"https://www.lenoxcontradance.org/\\" target=\\"_blank\\">Lenox, MA</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Friday, June 27, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/cojiroduo\\" target=\\"_blank\\">Cojiro</a> with Grace Hendrickson-Jones",\n'
      + '"location": "<a href=\\"https://www.hudsonvalleydance.org/contra\\" target=\\"_blank\\">Burlington, VT</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, June 28, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/cojiroduo\\" target=\\"_blank\\">Cojiro</a> with Grace Hendrickson-Jones",\n'
      + '"location": "<a href=\\"https://www.contramontreal.org/\\" target=\\"_blank\\">Montreal, QC</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, July 19, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/cojiroduo\\" target=\\"_blank\\">Cojiro</a> with Grace Hendrickson-Jones",\n'
      + '"location": "<a href=\\"https://www.montpeliercontradance.org/\\" target=\\"_blank\\">Montpelier, VT</a>",\n'
      + '"event": "Waltz session + contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Friday, July 25, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/thestarcharters\\" target=\\"_blank\\">The Star Charters</a>",\n'
      + '"location": "<a href=\\"https://rehobothcontradance.com/\\" target=\\"_blank\\">Rehoboth, MA</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, July 26, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/thestarcharters\\" target=\\"_blank\\">The Star Charters</a>",\n'
      + '"location": "Salem, NY",\n'
      + '"event": "Private event"\n'
    + '},\n'
    + '{\n'
      + '"date": "Friday, August 22, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/thestarcharters\\" target=\\"_blank\\">The Star Charters</a>",\n'
      + '"location": "<a href=\\"https://www.facebook.com/groups/bangorcontra/\\" target=\\"_blank\\">Bangor, ME</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, August 23, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/thestarcharters\\" target=\\"_blank\\">The Star Charters</a>",\n'
      + '"location": "<a href=\\"https://upcoming.kennebec-contra.org/\\" target=\\"_blank\\">Hallowell, ME</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Sunday, August 24, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/thestarcharters\\" target=\\"_blank\\">The Star Charters</a>",\n'
      + '"location": "Lewiston, ME",\n'
      + '"event": "Fiddler\'s Rendezvous Concert"\n'
    + '},\n'
    + '{\n'
      + '"date": "Thursday, September 4, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/cojiroduo\\" target=\\"_blank\\">Cojiro</a>",\n'
      + '"location": "<a href=\\"https://www.neffa.org/thursday-contras/\\" target=\\"_blank\\">Concord, MA</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, September 6, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/cojiroduo\\" target=\\"_blank\\">Cojiro</a>",\n'
      + '"location": "<a href=\\"https://www.facebook.com/groups/726222849231519/\\" target=\\"_blank\\">Falmouth, ME</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Sunday, September 7, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/cojiroduo\\" target=\\"_blank\\">Cojiro</a>",\n'
      + '"location": "<a href=\\"https://www.hackmatackplayhouse.org/contra-dances\\" target=\\"_blank\\">Berwick, ME</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, September 20, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/thestarcharters\\" target=\\"_blank\\">The Star Charters</a>",\n'
      + '"location": "<a href=\\"https://www.montpeliercontradance.org/\\" target=\\"_blank\\">Montpelier, VT</a>",\n'
      + '"event": "Waltz session + contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Wednesday, October 1, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/cojiroduo\\" target=\\"_blank\\">Cojiro</a> with Ben Graubart",\n'
      + '"location": "<a href=\\"https://www.bfms.org/squarecontra.php\\" target=\\"_blank\\">Baltimore, MD</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Thursday, October 2, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/cojiroduo\\" target=\\"_blank\\">Cojiro</a> with Ben Graubart",\n'
      + '"location": "<a href=\\"https://thursdaycontra.com/\\" target=\\"_blank\\">Philadelphia, PA</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Friday, October 3, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/cojiroduo\\" target=\\"_blank\\">Cojiro</a> with Ben Graubart",\n'
      + '"location": "<a href=\\"https://glenechopark.org/social-dances\\" target=\\"_blank\\">Glen Echo, MD</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, October 4, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/cojiroduo\\" target=\\"_blank\\">Cojiro</a> with Ben Graubart",\n'
      + '"location": "<a href=\\"https://cdny.org/\\" target=\\"_blank\\">New York, NY</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Sunday, October 5, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/thestarcharters\\" target=\\"_blank\\">The Star Charters</a> with Ben Graubart",\n'
      + '"location": "<a href=\\"https://www.brooklyncontra.org/\\" target=\\"_blank\\">New York, NY</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Friday, October 10, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/thestarcharters\\" target=\\"_blank\\">The Star Charters</a>",\n'
      + '"location": "<a href=\\"https://www.danceflurry.org/series/albany-contradance/\\" target=\\"_blank\\">Albany, NY</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, October 11, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/thestarcharters\\" target=\\"_blank\\">The Star Charters</a>",\n'
      + '"location": "<a href=\\"https://www.hudsonvalleydance.org/contra\\" target=\\"_blank\\">Poughkeepsie, NY</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Friday, November 7, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/cojiroduo\\" target=\\"_blank\\">Cojiro</a> with Grace Hendrickson-Jones",\n'
      + '"location": "<a href=\\"https://belfastflyingshoes.org/\\" target=\\"_blank\\">Belfast, ME</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, November 8, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/cojiroduo\\" target=\\"_blank\\">Cojiro</a> with Grace Hendrickson-Jones",\n'
      + '"location": "<a href=\\"https://www.facebook.com/SurryContraDance/\\" target=\\"_blank\\">Surry, ME</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Sunday, November 9, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/cojiroduo\\" target=\\"_blank\\">Cojiro</a> with Grace Hendrickson-Jones",\n'
      + '"location": "<a href=\\"https://www.commonfloorcontra.dance/\\" target=\\"_blank\\">Portland, ME</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, November 15, 2025",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/cojiroduo\\" target=\\"_blank\\">Cojiro</a>",\n'
      + '"location": "<a href=\\"https://topshamcontra.org/\\" target=\\"_blank\\">Topsham, ME</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, January 3, 2026",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/thestarcharters\\" target=\\"_blank\\">The Star Charters</a>",\n'
      + '"location": "<a href=\\"https://www.worcesterdance.org/\\" target=\\"_blank\\">Worcester. MA</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Wednesday, January 21, 2026",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/thestarcharters\\" target=\\"_blank\\">The Star Charters</a>",\n'
      + '"location": "<a href=\\"http://amherstcontra.org/\\" target=\\"_blank\\">Amherst, MA</a>",\n'
      + '"event": "Contra dance"\n'
    + '}\n'
  + ']\n'
+ '}]\n'
