var gigs = '[{'
+ '"gigs": [\n'
    + '{\n'
      + '"date": "Friday, January 11, 2019",\n'
      + '"who": "Jess",\n'
      + '"band": "<a href=\\"https://www.facebook.com/pepperjackcontra/\\" target=\\"_blank\\">Pepperjack</a> with Ben Graubart",\n'
      + '"location": "<a href=\\"http://www.lcfd.org/sf/circleleft.html/\\" target=\\"_blank\\">Oakland, CA</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Sunday, January 27, 2019",\n'
      + '"who": "Jess",\n'
      + '"band": "Jess & Derry",\n'
      + '"location": "<a href=\\"https://www.bacds.org/series/contra/san_jose/\\" target=\\"_blank\\">San Jose, CA</a>",\n'
      + '"event": "Teen contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Thursday, February 7, 2019",\n'
      + '"who": "Jess & Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/pepperjackcontra/\\" target=\\"_blank\\">Pepperjack</a> with Mark",\n'
      + '"location": "Santa Clara, CA",\n'
      + '"event": "House concert"\n'
    + '},\n'
    + '{\n'
      + '"date": "Friday, February 8, 2019",\n'
      + '"who": "Jess & Mark",\n'
      + '"band": "Jess & Mark",\n'
      + '"location": "<a href=\\"https://www.bacds.org/series/contra/san_jose/\\" target=\\"_blank\\">San Jose, CA</a>",\n'
      + '"event": "Teen contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Sunday, February 17, 2019",\n'
      + '"who": "Jess",\n'
      + '"band": "Jess, Scott Jespersen & Chris Knepper",\n'
      + '"location": "<a href=\\"https://www.bacds.org/series/contra/san_jose/\\" target=\\"_blank\\">San Jose, CA</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, March 2, 2019",\n'
      + '"who": "Jess",\n'
      + '"band": "Jess, Chris Knepper & Christopher Jacoby",\n'
      + '"location": "<a href=\\"http://www.bacds.org/series/contra/san_francisco/\\" target=\\"_blank\\">San Francisco, CA</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, March 30, 2019",\n'
      + '"who": "Jess",\n'
      + '"band": "Jess, Derry & Jeff Spero",\n'
      + '"location": "<a href=\\"http://www.bacds.org/series/contra/palo_alto/\\" target=\\"_blank\\">Palo Alto, CA</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Friday, April 5, 2019",\n'
      + '"who": "Jess",\n'
      + '"band": "<a href=\\"https://www.facebook.com/pepperjackcontra/\\" target=\\"_blank\\">Pepperjack</a>",\n'
      + '"location": "<a href=\\"https://www.facebook.com/groups/2526653690696415\\" target=\\"_blank\\">Palo Alto, CA</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, April 6, 2019",\n'
      + '"who": "Jess",\n'
      + '"band": "Jess & Will Wheeler",\n'
      + '"location": "<a href=\\"http://www.bacds.org/series/contra/san_francisco/\\" target=\\"_blank\\">San Francisco, CA</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, April 13, 2019",\n'
      + '"who": "Jess",\n'
      + '"band": "Jess & Daniel Steinberg",\n'
      + '"location": "<a href=\\"https://www.bacds.org/series/contra/san_jose/\\" target=\\"_blank\\">San Jose, CA</a>",\n'
      + '"event": "Teen contra"\n'
    + '},\n'
    + '{\n'
      + '"date": "Sunday, April 21, 2019",\n'
      + '"who": "Jess",\n'
      + '"band": "Jess & Patti Cobb",\n'
      + '"location": "<a href=\\"https://www.bacds.org/series/contra/san_jose/\\" target=\\"_blank\\">San Jose, CA</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Friday, May 3, 2019",\n'
      + '"who": "Jess",\n'
      + '"band": "Jess, Scott Jespersen & Will Wheeler",\n'
      + '"location": "<a href=\\"https://www.facebook.com/groups/2526653690696415\\" target=\\"_blank\\">Palo Alto, CA</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, May 11, 2019",\n'
      + '"who": "Jess",\n'
      + '"band": "Jess & Will Wheeler",\n'
      + '"location": "<a href=\\"https://www.bacds.org/series/contra/san_jose/\\" target=\\"_blank\\">San Jose, CA</a>",\n'
      + '"event": "Teen contra"\n'
    + '}\n'
  + ']\n'
+ '}]\n'
