var gigs = '[{'
+ '"gigs": [\n'
    + '{\n'
      + '"date": "Saturday, January 3, 2026",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/thestarcharters\\" target=\\"_blank\\">The Star Charters</a>",\n'
      + '"location": "<a href=\\"https://www.worcesterdance.org/\\" target=\\"_blank\\">Worcester. MA</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Wednesday, January 21, 2026",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "<a href=\\"https://www.facebook.com/thestarcharters\\" target=\\"_blank\\">The Star Charters</a>",\n'
      + '"location": "<a href=\\"http://amherstcontra.org/\\" target=\\"_blank\\">Amherst, MA</a>",\n'
      + '"event": "Contra dance"\n'
    + '}\n'
  + ']\n'
+ '}]\n'
