// Tunes represented as JSON.
var tunes = '[{'
  + '"tunes": [\n'
    + '{\n'
      + '"name": "Avery\'s Jig",\n'
      + '"time": "Jig",\n'
      + '"key": "D dor",\n'
      + '"description": "An early Mark jig written for a roleplay character, who rescued a fiddler from a predicament and received a tune in return.",\n'
      + '"date": "April 2013",\n'
      + '"author": "Mark",\n'
      + '"audio": "averys jig",\n'
      + '"pdf": "Averys Jig"\n'
    + '},\n'
    + '{\n'
      + '"name": "Behind the Waterfall",\n'
      + '"time": "Reel",\n'
      + '"key": "D dor/mix",\n'
      + '"description": "Jess wrote this one. The name comes from the sound of agonizing and patient practice, best captured by Makar from the Wind Waker (Zelda 2003), who can be heard scratching out an eternal practice session behind a waterfall.",\n'
      + '"date": "May 2017",\n'
      + '"author": "Jess",\n'
      + '"audio": "behind the waterfall",\n'
      + '"pdf": "Behind the Waterfall"\n'
    + '},\n'
    + '{\n'
      + '"name": "Curiosity Shop",\n'
      + '"time": "March",\n'
      + '"key": "A min",\n'
      + '"description": "A kind of Latin jazzy jam in a half time feel for stompy dances, inspired by some of the stompy half time jams played by <a href=\\"https://www.buddysystemband.com/\\" target=\\"_blank\\">Buddy System</a>. It makes Mark feel like he\'s strolling through a market with a cold beverage on a hot summer day looking for something rare and strange.",\n'
      + '"date": "March 2019",\n'
      + '"author": "Mark",\n'
      + '"audio": "curiosity shop",\n'
      + '"pdf": "Curiosity Shop"\n'
    + '},\n'
    + '{\n'
      + '"name": "Delilah & Me",\n'
      + '"time": "Slow reel",\n'
      + '"key": "G maj",\n'
      + '"description": "A tune to remember the service dog of a friend and all around Good Girl named <a href=\\"img/delilah.jpg\\" target=\\"_blank\\">Delilah</a>.",\n'
      + '"date": "May 2018",\n'
      + '"author": "Mark",\n'
      + '"audio": "delilah & me",\n'
      + '"pdf": "Delilah & Me"\n'
    + '},\n'
    + '{\n'
      + '"name": "February Summer",\n'
      + '"time": "Waltz",\n'
      + '"key": "D mix",\n'
      + '"description": "We collaborated on this one to commemorate our friend Derry\'s birthday, during a February filled with summery days playing music outside. We ended up with a mildly Scandinavian sounding mixolydian waltz.",\n'
      + '"date": "February 2018",\n'
      + '"author": "Mark and Jess",\n'
      + '"audio": "february summer",\n'
      + '"pdf": "February Summer"\n'
    + '},\n'
    + '{\n'
      + '"name": "Get Dunked On",\n'
      + '"time": "Reel",\n'
      + '"key": "D min",\n'
      + '"description": "This is a contra dance friendly reinterpretation of <a href=\\"https://youtu.be/B2jVbSI9H4o\\" target=\\"_blank\\">Megalovania</a> by Toby Fox, which is most famous as a boss theme in the game Undertale (also by Toby Fox) and for being good.",\n'
      + '"date": "March 2019",\n'
      + '"author": "Mark and Jess",\n'
      + '"audio": "get dunked on",\n'
      + '"pdf": "Get Dunked On"\n'
    + '},\n'
    + '{\n'
      + '"name": "Kittelish",\n'
      + '"time": "Jig",\n'
      + '"key": "A mix",\n'
      + '"description": "A 3-part jig, the C part of which came to Mark when he was in a lab meeting. Named because that part sounds just complicated enough and with a sweeping enough chord progression that it reminds us of something Jeremey Kittel might play.",\n'
      + '"date": "July 2017",\n'
      + '"author": "Mark",\n'
      + '"audio": "kittelish",\n'
      + '"pdf": "Kittelish"\n'
    + '},\n'
    + '{\n'
      + '"name": "Leggy Boy Bat",\n'
      + '"time": "Jig",\n'
      + '"key": "D maj",\n'
      + '"description": "A 4-part jig named after another <a href=\\"https://twitter.com/deaths_cool/status/940263487095361538\\" target=\\"_blank\\">Good Dog</a>. The tune is too long because his legs are too long.",\n'
      + '"date": "June 2018",\n'
      + '"author": "Mark",\n'
      + '"audio": "leggy boy bat",\n'
      + '"pdf": "Leggy Boy Bat"\n'
    + '},\n'
    + '{\n'
      + '"name": "Made by the Sea",\n'
      + '"time": "Reel",\n'
      + '"key": "E mix",\n'
      + '"description": "Mark wrote this because he was inspired by a <a href=\\"https://clips.twitch.tv/HonestAmazonianStarlingDxAbomb\\" target=\\"_blank\\">legendary stream</a> of Final Fantasy 7 by Shaun and Jen in which Jen asserted her beliefs on how shells are made.",\n'
      + '"date": "March 2018",\n'
      + '"author": "Mark",\n'
      + '"audio": "(a normal shell,) made by the sea",\n'
      + '"pdf": "(A Normal Shell,) Made by the Sea"\n'
    + '},\n'
    + '{\n'
      + '"name": "Meeting of the Minds",\n'
      + '"time": "Reel",\n'
      + '"key": "G mix",\n'
      + '"description": "We wrote this together after a long visit by Mark to the Bay Area to commemorate a real nice and productive time together. As pointed out by Jess\' bandmate Scott, the ending leads into \\"Get Back.\\", if you really want to go there.",\n'
      + '"date": "May 2018",\n'
      + '"author": "Mark and Jess",\n'
      + '"audio": "meeting of the minds",\n'
      + '"pdf": "Meeting of the Minds"\n'
    + '},\n'
    + '{\n'
      + '"name": "Moonbean",\n'
      + '"time": "March",\n'
      + '"key": "G mix",\n'
      + '"description": "An attempt to write a groovy march in a half time feel that sort of turned into a fairy dance.",\n'
      + '"date": "March 2019",\n'
      + '"author": "Mark and Jess",\n'
      + '"audio": "moonbean",\n'
      + '"pdf": "Moonbean"\n'
    + '},\n'
    + '{\n'
      + '"name": "No Sleep Tonight",\n'
      + '"time": "Reel",\n'
      + '"key": "F# min",\n'
      + '"description": "Mark wrote this one because his sleeping habits are terrible. Fondly remembering nights climbing into bed while the birds start screaming outside before dawn. A bit hard to tell whether it\'s actually F# minor or A major. Either way, starts on a D chord.",\n'
      + '"date": "November 2017",\n'
      + '"author": "Mark",\n'
      + '"audio": "no sleep tonight",\n'
      + '"pdf": "No Sleep Tonight"\n'
    + '},\n'
    + '{\n'
      + '"name": "Reel for Gins the Cat",\n'
      + '"time": "Reel",\n'
      + '"key": "D maj",\n'
      + '"description": "Ode to Mark\'s cat <a href=\\"img/ginny.gif\\" target=\\"_blank\\">Ginseng</a>. She\'s extremely fluffy and acts like a princess, but is secretly very sweet.",\n'
      + '"date": "July 2015",\n'
      + '"author": "Mark",\n'
      + '"audio": "reel for gins the cat",\n'
      + '"pdf": "Reel for Gins the Cat"\n'
    + '},\n'
    + '{\n'
      + '"name": "Reviewer 3",\n'
      + '"time": "Reel",\n'
      + '"key": "D min",\n'
      + '"description": "Mark wrote this tune for a peer reviewer who trashed his conference paper submission which was then rejected. Originally it was angry sounding but is now jazzy instead because that makes it funnier. Read the review and listen along <a href=\\"https://youtu.be/fBzdVtq2Wo8\\" target=\\"_blank\\">here</a>.",\n'
      + '"date": "February 2019",\n'
      + '"author": "Mark",\n'
      + '"audio": "reviewer 3",\n'
      + '"pdf": "Reviewer 3"\n'
    + '},\n'
    + '{\n'
      + '"name": "The Silver",\n'
      + '"time": "Reel",\n'
      + '"key": "G mix / D dor",\n' 
      + '"description": "A hypnotic sort of reel we co-wrote on the mandolin Jess owns but doesn\'t play. The name references the Broken Earth series by N. K. Jemisin, which is incredibly good, and you need to read it if you haven\'t.",\n'
      + '"date": "September 2018",\n'
      + '"author": "Mark and Jess",\n'
      + '"audio": "the silver",\n'
      + '"pdf": "The Silver"\n'
    + '},\n'    
    + '{\n'
      + '"name": "Spider Jive",\n'
      + '"time": "Reel",\n'
      + '"key": "A min",\n'
      + '"description": "Mark and Derry (from Pepperjack) collaborated on this for Jess\'s birthday. Somehow it turned into a Halloween tune. Named by Jess for its Undertale vibes.",\n'
      + '"date": "May 2018",\n'
      + '"author": "Mark and Derry",\n'
      + '"audio": "spider jive",\n'
      + '"pdf": "Spider Jive"\n'
    + '},\n'
    + '{\n'
      + '"name": "The Shot in the Dark",\n'
      + '"time": "Jig",\n'
      + '"key": "D dor",\n'
      + '"description": "A twisty jig named after the ship that our D&D party sailed in during a particularly long arc at sea in which many friends and enemies were made.",\n'
      + '"date": "February 2018",\n'
      + '"author": "Mark",\n'
      + '"audio": "the shot in the dark",\n'
      + '"pdf": "The Shot in the Dark"\n'
    + '},\n'
    + '{\n'
      + '"name": "Toujours l\'Audace",\n'
      + '"time": "Reel",\n'
      + '"key": "A dor",\n'
      + '"description": "Written in honor of Jess\'s D&D character, Chaszwik. Named after his frankly overpowered ability which allows him to roll about 70 damage dice on every attack. Chaszwik rulz ok.",\n'
      + '"date": "November 2016",\n'
      + '"author": "Mark",\n'
      + '"audio": "toujours laudace",\n'
      + '"pdf": "Toujours lAudace"\n'
    + '},\n'
    + '{\n'
      + '"name": "Tune from Under a Rock",\n'
      + '"time": "Reel",\n'
      + '"key": "G maj",\n'
      + '"description": "Mark wrote this on Christmas Eve. Named for a tune which is well known on the fairy island of Emain Abla (yeah we\'re talking about D&D again), and often played by a dryad flautist named Felim.",\n'
      + '"date": "December 2017",\n'
      + '"author": "Mark",\n'
      + '"audio": "tune from under a rock",\n'
      + '"pdf": "Tune From Under a Rock"\n'
    + '},\n'
    + '{\n'
      + '"name": "We Dodge Again",\n'
      + '"time": "Reel",\n'
      + '"key": "G min",\n'
      + '"description": "In commemoration of competitive Guild Wars 2 thief player <a href=\\"https://www.youtube.com/watch?v=KDlVYcXoqPA\\" target=\\"_blank\\">Sindrener</a>\'s ability to see an enemy thief\'s intent to steal in his eyes. One of the scarier sounding tunes here. \\"I listened to it [...]\\" - Sindrener.",\n'
      + '"date": "May 2017",\n'
      + '"author": "Mark",\n'
      + '"audio": "we dodge again",\n'
      + '"pdf": "We Dodge Again"\n'
    + '}\n'
  + ']\n'
+ '}]\n'
